FROM ubuntu:20.04

RUN export DEBIAN_FRONTEND="noninteractive" && export TZ="America/New_York"
RUN yes |unminimize
RUN apt-get -y update && apt-get -y upgrade && apt-get -y install sudo less vim micro git golang-go bzip2

# set timezone
RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
RUN dpkg-reconfigure --frontend noninteractive tzdata

COPY ./rhythm_dev.tar.bz2 /
RUN bunzip2 rhythm_dev.tar.bz2 |xargs -I{} tar -xf {}
COPY ./Dockerfile rhythm_dev/
RUN bash ./pwsh-install.sh
RUN go get -u github.com/justjanne/powerline-go
RUN source .bash_profile
