FROM jjrobertson14/rhythm_dev:created_rhythm_user

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/New_York
RUN apt-get update -y && apt-get upgrade -y

# set timezone
RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
RUN dpkg-reconfigure --frontend noninteractive tzdata

# add files to /home/rhythm
COPY ./home_rhythm.tar.bz2 /home/rhythm
COPY ./unzip-home_rhythm.sh /
RUN ./unzip-home_rhythm.sh
# run initial commands as rhythm
RUN cd /home/rhythm && sudo -u rhythm go get -u github.com/justjanne/powerline-go && sudo -u rhythm ln -s /rhythm_dev .
