FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/New_York
RUN yes |unminimize
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y sudo less vim micro git golang-go bzip2

# set timezone
RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
RUN dpkg-reconfigure --frontend noninteractive tzdata

COPY ./rhythm_dev.tar.bz2 /
RUN bunzip2 rhythm_dev.tar.bz2 |xargs -I{} tar -xf {}
COPY ./Dockerfile rhythm_dev/
RUN bash ./rhythm_dev/pwsh-install.sh
RUN go get -u github.com/justjanne/powerline-go
RUN source ./rhythm_dev/.bash_profile
